### ISSUE TITLE
Change Settings or Dashboard icon - they are too similar

### ISSUE THREAD

**Issue by Avaray** [KindaBrazy/LynxHub#15]
Settings and Dashboard icons are too similar

I see two solutions:
1. Change dashboard icon for something that is not similar to `Cogwheel` icon
2. Change Settings icon to [Slider](https://icones.js.org/collection/all?s=sliders) one.

**Comment by KindaBrazy** [comment]
I've already changed the dashboard icon for the next update, and I'll also switch the settings icon to a slider to avoid them looking too similar. Thanks for the suggestion!
