### ISSUE TITLE
Add a option to hide not interested project and also stat info.

### ISSUE THREAD

**Issue by shivshankar11** [KindaBrazy/LynxHub#16]
**Is your feature request related to a problem? Please describe.**
Add a option to hide not interested project and also stat info.

Add a option to hide creator, stars, fork, issues, size. 
i only want to see project title, launch, update button nothing else.

something like this. StablityMatrix
![image](https://github.com/user-attachments/assets/6b379a15-91f1-48cb-8b24-cc9f486698c7)

**Comment by KindaBrazy** [comment]
For projects you're not interested in, you can pin your favorites, hide the 'All' category, and enable the 'Pin' category.
- **How?** Next to the search bar on the home page, there's a filter button where you can toggle categories.


As for customizing cards to show or hide specific info, **I'm currently working on that!**
