### ISSUE TITLE
LynxHub opens wrong URL for tts-generation-webui

### ISSUE THREAD

**Issue by WanderFox** [KindaBrazy/LynxHub#19]
When you launch [tts-generation-webui] it opens first link from Terminal: http://localhost:3000/
But it must open second one: http://127.0.0.1:7770/ 

![image](https://github.com/user-attachments/assets/c0b79bfc-77f1-423e-b4c6-31fcad448b8d)
![image](https://github.com/user-attachments/assets/fe13cc03-a00d-42dc-b42c-07a9f35c396d)

**Comment by KindaBrazy** [comment]
Can you share a screenshot where the second address (http://127.0.0.1:7770) is outputted in the terminal?

**Comment by WanderFox** [comment]
After few time (~30sec) it proceeds to load modules (image below)
![image](https://github.com/user-attachments/assets/2a41b6d4-e201-4181-9cd7-92cc2b031187)

After this command, it loads the correct page in a browser
![image](https://github.com/user-attachments/assets/b094c7b3-44ca-4aa9-8312-92bbe6994128)

![image](https://github.com/user-attachments/assets/f26924d1-5d58-4cf6-9515-698290d69c32)

**Comment by KindaBrazy** [comment]
Thank you so much for the detailed screenshots.

**The output doesn’t contain the final address**, so LynxHub catches the address from the **terminal output** and opens it in the browser.

Is the `7770` port always static and doesn’t change?
I’ll try having it open `localhost:7770` in the browser once the terminal output **finishes loading**.

**Comment by WanderFox** [comment]
Yeah, port the same every time. It's really unnecessary to make exceptions for every new AI-Workspace. As a universal solution, you can make it possible to paste your own URL inside the internal browser for cases like that. Just copy-paste and you continue work inside LynxHub

**Comment by KindaBrazy** [comment]
Got it **solved through the module**! Please **update the module** in the app, and TTS should now open correctly. 

I made LynxHub modular so each webUI can have its own functionality and address detection, as I think it’s more convenient to auto-detect and open URLs for users. However, I will also add the option to open custom URLs and include a history feature to make it easier and faster to reopen previously used URLs.
